# Generated by Django 5.2.12 on 2026-03-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=150)),
                ('icerik', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='Uye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=120)),
                ('telefon', models.CharField(blank=True, max_length=30)),
                ('adres', models.TextField(blank=True)),
                ('aidat_durumu', models.CharField(choices=[('Odendi', 'Ödendi'), ('Odenmedi', 'Ödenmedi'), ('Kismi', 'Kısmi')], default='Odenmedi', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='uye_fotolari/')),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
